version: '3.9'

services:
  laravelapp:
    container_name: sistem_gudang
    image: qika219/sistem_gudang:1.0.1
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sistem_gudang
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}

    