version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=sistem_gudang
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sistem_gudang
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
